---
title: "R&D Days"
format: html
---

## Outline

- Origin of the R-ArcGIS Bridge
- When it was created
- arcgisbinding & what it does
  - Read and write local data 
    - R-spatial ecosystem grown out of this need (for the most part) due to developments in GDAL
  - create geoprocessing script tools
- Limitations: requires Pro install (meaning windows and a license)
- R has grown considerably and so has ArcGIS, notably with our location services
- We are introducing a new R package `{arcgis}`
- `arcgis` brings ArcGIS to R users where they work
- `arcgis` is a meta package providing access to location services
- the first iteration consists of 2 packages `{arcgisutils}` and `{arcgislayers}`
  - arcgisutils - developer oriented toolkit for creating other packages
    - esri json parsing and serialization
    - authorization functionality
  - arcgislayers - workhorse for reading and writing to Feature Services as well as reading Image Servers
- opens up the R-ArcGIS Bridge project to be more than just arcgisbinding
- our mid-term goal is to address gaps in the R ecosystem for routing and geocoding
- long term we can add more location services such as enrichment or analysis
- allows us to build outside of the bounds of just Pro and Location services now
- add packages like geoanalytics R package
- compare and contrast arcgisbinding and arcgis
- demo
  - anonymous access
  - authorization using OAuth2 client and code flows
  - opening a feature server
  - dplyr integration
  - writing a new feature server 
