# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

get_envelope_z <- function(sf, depth = 0L) {
    .Call(`_arcgis_get_envelope_z`, sf, depth)
}

get_envelope_zm <- function(sf, depth = 0L) {
    .Call(`_arcgis_get_envelope_zm`, sf, depth)
}

sfc_point_xy <- function(points) {
    .Call(`_arcgis_sfc_point_xy`, points)
}

sfc_point_xyz <- function(points) {
    .Call(`_arcgis_sfc_point_xyz`, points)
}

sfc_point_xyzm <- function(points) {
    .Call(`_arcgis_sfc_point_xyzm`, points)
}

sfc_point_impl <- function(points) {
    .Call(`_arcgis_sfc_point_impl`, points)
}

sfc_multipoint_impl <- function(mpoints) {
    .Call(`_arcgis_sfc_multipoint_impl`, mpoints)
}

sfc_linestring_impl <- function(mpoints) {
    .Call(`_arcgis_sfc_linestring_impl`, mpoints)
}

sfc_multilinestring_inner_impl <- function(mpoints) {
    .Call(`_arcgis_sfc_multilinestring_inner_impl`, mpoints)
}

sfc_multilinestring_impl <- function(mlines) {
    .Call(`_arcgis_sfc_multilinestring_impl`, mlines)
}

sfg_polygon_impl <- function(mply) {
    .Call(`_arcgis_sfg_polygon_impl`, mply)
}

sfc_polygon_impl <- function(mply) {
    .Call(`_arcgis_sfc_polygon_impl`, mply)
}

sfg_multipolygon_inner_impl <- function(mply) {
    .Call(`_arcgis_sfg_multipolygon_inner_impl`, mply)
}

sfg_multipolygon_impl <- function(mply) {
    .Call(`_arcgis_sfg_multipolygon_impl`, mply)
}

sfc_multipolygon_impl <- function(mply) {
    .Call(`_arcgis_sfc_multipolygon_impl`, mply)
}

